# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f81b29b4c3e9d39990b53be07d899bcc052a4141e471956dc5228c9a6f3d5816c80c5d62d67512d67132d62d91d14db983c2799a6c08709570fa3cc24a426564

test:
  secret_key_base: 3e4585af2aaf37eabe66ecfb976223fbd1667fdb8661840efc83eddfc9a507581730a14ec4b53cc9a2d8ab8751eeba15bc91861d11fca9c82c49be373687a254

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
